version: '3.8'
services:
    api:
        build: .
        image: rugby_manager_api
        container_name: rm-ctr
        ports:
            - "3000:3000"
        links:
            - mongo
        volumes:
            - ./:/home/app
        
    mongo:
        image: mongo:4.2
        container_name: mongodb-rm
        ports:
            - "27017:27017"
        volumes:
            - ./data:/data/db
