version: '3.8'
services:
    api:
        build: .
        container_name: rm-api
        ports:
            - "3000:3000"
        links:
            - mongo
        env_file: .env
        
    mongo:
        image: mongo:4.2
        container_name: mongodb
        ports:
            - "27017:27017"
        volumes:
            - ./data:/data/db
